#!/usr/bin/env python3
"""使用 CuRobo V2 RobotBuilder 为 ROKAE SR5 自动生成碰撞球。

替代手工 Bubblify 流程，输出与现有项目格式兼容的 collision_spheres YAML。

用法:
    # 基本用法（使用默认参数）
    python scripts/generate_rokae_spheres.py

    # 调整球密度（更多球 = 更精确但更慢）
    python scripts/generate_rokae_spheres.py --sphere-density 2.0

    # 可视化检查拟合效果
    python scripts/generate_rokae_spheres.py --visualize

    # 只重新拟合某个 link
    python scripts/generate_rokae_spheres.py --refit-link XMS5-R800-W4G3B4C_link6

    # 完整流程：生成 + 压测对比
    python scripts/generate_rokae_spheres.py --stress-test
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import torch
import yaml

# 添加项目根目录到 path
WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(WORKSPACE_ROOT))

# CuRobo V2 路径
CUROBO_PATH = WORKSPACE_ROOT / "third_party" / "curobo"
if str(CUROBO_PATH) not in sys.path:
    sys.path.insert(0, str(CUROBO_PATH))

# CuRobo V2 imports
from curobo.sphere_fit import SphereFitType
from curobo.robot_builder import RobotBuilder

# 默认路径
DEFAULT_URDF = WORKSPACE_ROOT / "robot_assets" / "ROKAE" / "robot" / "curobo" / "ROKAE_SR5_0.9C.urdf"
DEFAULT_ASSET_PATH = WORKSPACE_ROOT / "robot_assets" / "ROKAE" / "robot" / "curobo"
DEFAULT_OUTPUT = WORKSPACE_ROOT / "robot_assets" / "ROKAE" / "robot" / "spheres" / "ROKAE_SR5_0.9C_spherized.yml"
DEFAULT_ROBOT_CONFIG = WORKSPACE_ROOT / "robot_assets" / "ROKAE" / "robot" / "xms5_r800_w4g3b4c_robot.yml"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="使用 CuRobo V2 为 ROKAE SR5 自动生成碰撞球",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # 输入路径
    parser.add_argument("--urdf", type=Path, default=DEFAULT_URDF, help="URDF 文件路径")
    parser.add_argument("--asset-path", type=Path, default=DEFAULT_ASSET_PATH, help="mesh 资产目录")
    parser.add_argument("--robot-config", type=Path, default=DEFAULT_ROBOT_CONFIG, help="现有 robot config（用于提取 cspace 等）")

    # 输出路径
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="输出 spheres YAML 路径")
    parser.add_argument("--output-full-config", type=Path, default=None, help="输出完整 robot config（可选）")

    # 球拟合参数
    parser.add_argument("--sphere-density", type=float, default=0.3, help="球密度倍数（默认 0.3，约 200 球）")
    parser.add_argument("--num-spheres", type=int, default=None, help="每个 link 的显式球数（覆盖 sphere-density）")
    parser.add_argument("--fit-type", type=str, default="MORPHIT", choices=["SURFACE", "VOXEL", "MORPHIT"], help="拟合算法（默认 MORPHIT）")
    parser.add_argument("--surface-radius", type=float, default=0.002, help="SURFACE 模式固定半径(m)（默认 0.002）")
    parser.add_argument("--coverage-weight", type=float, default=None, help="MorphIt coverage 损失权重（默认 1000）")
    parser.add_argument("--protrusion-weight", type=float, default=None, help="MorphIt protrusion 损失权重（默认 10）")
    parser.add_argument("--iterations", type=int, default=200, help="MorphIt 迭代次数")

    # 碰撞矩阵参数
    parser.add_argument("--num-collision-samples", type=int, default=1000, help="碰撞裁剪采样数")
    parser.add_argument("--no-prune", action="store_true", help="跳过碰撞裁剪（更快但不优化）")

    # 特殊操作
    parser.add_argument("--refit-link", type=str, default=None, help="只重新拟合指定 link")
    parser.add_argument("--from-config", type=Path, default=None, help="从现有 config 加载并编辑")

    # 可视化
    parser.add_argument("--visualize", action="store_true", help="启动 Viser 可视化服务器")
    parser.add_argument("--viz-port", type=int, default=8080, help="Viser 端口")
    parser.add_argument("--compute-metrics", action="store_true", help="计算并输出每个 link 的拟合质量指标")

    # 压测
    parser.add_argument("--stress-test", action="store_true", help="生成后运行压测对比")

    # 可复现性
    parser.add_argument("--seed", type=int, default=None, help="随机种子")

    return parser.parse_args()


def export_spheres_yaml(
    collision_spheres: dict,
    output_path: Path,
    urdf_path: str,
    source: str = "curobo_v2_robot_builder",
    notes: list[str] | None = None,
) -> None:
    """导出为项目标准的 collision_spheres YAML 格式。

    与 convert_bubblify_spheres.py 输出格式兼容。
    """
    total_spheres = sum(len(spheres) for spheres in collision_spheres.values())

    data = {
        "collision_spheres": collision_spheres,
        "metadata": {
            "source": source,
            "urdf_path": urdf_path,
            "total_spheres": total_spheres,
            "links": list(collision_spheres.keys()),
            "exported_at_utc": datetime.now(timezone.utc).isoformat(),
            "notes": notes or [
                "Generated by CuRobo V2 RobotBuilder.fit_collision_spheres()",
                "MorphIt optimizer with adaptive sphere count per link",
            ],
        },
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(yaml.safe_dump(data, sort_keys=False, allow_unicode=True))

    print(f"\nSaved collision spheres to: {output_path}")
    print(f"  Links: {len(collision_spheres)}")
    print(f"  Total spheres: {total_spheres}")


def normalize_spheres_to_meters(collision_spheres: dict) -> dict:
    """Normalize fitted spheres to meters when mesh scale was effectively ignored.

    The active ROKAE URDF references STL meshes with ``scale=0.001``.  In the
    current cuRobo RobotBuilder path used here, the link-geometry fitting path
    can surface sphere centers/radii in the STL's raw millimeter scale.  Detect
    that case conservatively and convert to meters in-place.
    """
    if not collision_spheres:
        return collision_spheres

    sample_sphere = None
    for spheres in collision_spheres.values():
        if spheres:
            sample_sphere = spheres[0]
            break
    if sample_sphere is None:
        return collision_spheres

    center = sample_sphere.get("center", [])
    radius = float(sample_sphere.get("radius", 0.0))
    max_coord = max((abs(float(c)) for c in center), default=0.0)

    # Robot link-local collision spheres should be on the order of centimeters.
    # If values are in the tens/hundreds, they almost certainly came from raw mm STL units.
    if max_coord <= 10.0 and radius <= 10.0:
        return collision_spheres

    scale_radius = radius > 1.0
    radius_msg = "centers+radii" if scale_radius else "centers only"
    print(
        f"\nDetected oversized sphere units (max_coord={max_coord:.3f}, radius={radius:.3f}); "
        f"converting fitted spheres from millimeters to meters ({radius_msg})..."
    )
    for spheres in collision_spheres.values():
        for sphere in spheres:
            sphere["center"] = [float(c) / 1000.0 for c in sphere["center"]]
            if scale_radius:
                sphere["radius"] = float(sphere["radius"]) / 1000.0
    return collision_spheres


def build_new_robot(args: argparse.Namespace) -> None:
    """从 URDF 创建新的机器人配置。"""
    print(f"Building robot model from URDF: {args.urdf}")
    print(f"Asset path: {args.asset_path}")

    # 创建 builder
    builder = RobotBuilder(
        urdf_path=str(args.urdf),
        asset_path=str(args.asset_path),
        tool_frames=["tool0"],
    )

    print(f"Found {len(builder.tool_frames)} links in robot")

    # 拟合碰撞球
    print("\nFitting collision spheres...")
    fit_type = SphereFitType[args.fit_type]
    builder.fit_collision_spheres(
        sphere_density=args.sphere_density,
        num_spheres=args.num_spheres,
        fit_type=fit_type,
        surface_radius=args.surface_radius,
        coverage_weight=args.coverage_weight,
        protrusion_weight=args.protrusion_weight,
        iterations=args.iterations,
        compute_metrics=args.compute_metrics,
    )

    normalize_spheres_to_meters(builder.collision_spheres)

    print(f"Fitted {builder.num_spheres} spheres across {len(builder.collision_link_names)} links")

    # 输出质量指标
    if args.compute_metrics and builder.link_metrics:
        print(f"\n{'Link':<35s} {'n_sph':>5s} {'cover%':>7s} {'protr%':>7s} {'prot_mm':>8s} {'gap_mm':>7s} {'vol_ratio':>9s}")
        print("-" * 85)
        for link_name, m in builder.link_metrics.items():
            print(
                f"{link_name:<35s} {m.num_spheres:5d} "
                f"{m.coverage * 100:6.1f}% {m.protrusion * 100:6.1f}% "
                f"{m.protrusion_dist_mean * 1000:7.2f}mm "
                f"{m.surface_gap_mean * 1000:6.2f}mm "
                f"{m.volume_ratio:9.3f}"
            )

    # 计算碰撞矩阵
    print("\nComputing collision matrix...")
    builder.compute_collision_matrix(
        prune_collisions=not args.no_prune,
        num_samples=args.num_collision_samples,
    )

    print(f"Created collision ignore matrix with {len(builder.collision_matrix)} entries")

    # 构建配置
    config = builder.build()

    # 导出 spheres YAML（项目标准格式）
    export_spheres_yaml(
        collision_spheres=builder.collision_spheres,
        output_path=args.output,
        urdf_path=str(args.urdf),
        source="curobo_v2_robot_builder",
    )

    # 可选：导出完整 robot config
    if args.output_full_config:
        print(f"\nSaving full robot config to: {args.output_full_config}")
        builder.save(config, str(args.output_full_config))

    # 可视化
    if args.visualize:
        print(f"\nStarting visualization server at http://localhost:{args.viz_port}")
        print("Press Ctrl+C to stop")
        builder.visualize(config, port=args.viz_port, show_meshes=True)


def edit_existing_robot(args: argparse.Namespace) -> None:
    """编辑现有配置（重新拟合某个 link）。"""
    print(f"Loading robot configuration: {args.from_config}")

    builder = RobotBuilder.from_config(str(args.from_config))

    print(f"Loaded robot with {builder.num_spheres} spheres")

    if args.refit_link:
        print(f"\nRefitting spheres for link: {args.refit_link}")
        builder.refit_link_spheres(
            args.refit_link,
            sphere_density=args.sphere_density,
            coverage_weight=args.coverage_weight,
            protrusion_weight=args.protrusion_weight,
            iterations=args.iterations,
            compute_metrics=args.compute_metrics,
        )
        print(f"Refitted {len(builder.collision_spheres[args.refit_link])} spheres for {args.refit_link}")

    normalize_spheres_to_meters(builder.collision_spheres)

    if args.no_prune:
        builder.compute_collision_matrix(prune_collisions=False)
    else:
        builder.compute_collision_matrix(
            num_samples=args.num_collision_samples,
        )

    config = builder.build()

    # 导出 spheres YAML
    export_spheres_yaml(
        collision_spheres=builder.collision_spheres,
        output_path=args.output,
        urdf_path=str(args.urdf),
        source="curobo_v2_robot_builder_refit",
        notes=[f"Refitted link: {args.refit_link}"],
    )

    if args.output_full_config:
        print(f"\nSaving full robot config to: {args.output_full_config}")
        builder.save(config, str(args.output_full_config))

    if args.visualize:
        print(f"\nStarting visualization server at http://localhost:{args.viz_port}")
        print("Press Ctrl+C to stop")
        builder.visualize(config, port=args.viz_port, show_meshes=True)


def run_stress_test(args: argparse.Namespace) -> None:
    """运行压测对比（如果有 stress_test_rokae_pipeline.py）。"""
    stress_test_script = WORKSPACE_ROOT / "tests" / "stress_test_rokae_pipeline.py"
    if not stress_test_script.exists():
        print(f"\nStress test script not found: {stress_test_script}")
        return

    print("\nRunning stress test comparison...")
    import subprocess

    cmd = [
        sys.executable,
        str(stress_test_script),
        "--baseline-spheres", str(DEFAULT_OUTPUT),
        "--candidate-spheres", str(args.output),
    ]

    result = subprocess.run(cmd, cwd=str(WORKSPACE_ROOT))
    if result.returncode == 0:
        print("Stress test passed!")
    else:
        print(f"Stress test failed with return code {result.returncode}")


def main() -> None:
    args = parse_args()

    # 设置随机种子
    if args.seed is not None:
        import numpy as np
        np.random.seed(args.seed)
        torch.manual_seed(args.seed)

    # 验证输入
    if not args.urdf.exists():
        print(f"Error: URDF file not found: {args.urdf}")
        sys.exit(1)

    if args.from_config:
        edit_existing_robot(args)
    else:
        build_new_robot(args)

    # 压测
    if args.stress_test:
        run_stress_test(args)


if __name__ == "__main__":
    main()
